PERSONAJES = {
        "Susan": {"pelo": "blanco", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "mujer", "mejilla": "rojo", "boca": "grande", "nariz": "pequeña", "orejas": "normal", "cabeza": "normal"},
        "Claire": {"pelo": "rojo", "entradas": False, "ojos": "marron", "gafas": True, "sombrero": True, "barba": False, "bigote": False, "pendientes": True, "sexo": "mujer", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "normal", "cabeza": "grande"},
        "David": {"pelo": "amarillo", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": True, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "pequeña", "orejas": "normal", "cabeza": "normal"},
        "Anne": {"pelo": "negro", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": True, "sexo": "mujer", "mejilla": "normal", "boca": "pequeña", "nariz": "grande", "orejas": "normal", "cabeza": "grande"},
        "Robert": {"pelo": "marron", "entradas": False, "ojos": "azul", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "rojo", "boca": "grande", "nariz": "grande", "orejas": "normal", "cabeza": "normal"},
        "Anita": {"pelo": "amarillo", "entradas": False, "ojos": "azul", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "rojo", "boca": "pequeña", "nariz": "pequeña", "orejas": "pequeña", "cabeza": "pequeña"},
        "Joe": {"pelo": "amarillo", "entradas": False, "ojos": "marron", "gafas": True, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "pequeña", "cabeza": "normal"},
        "George": {"pelo": "amarillo", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": True, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "normal", "nariz": "normal", "orejas": "normal", "cabeza": "normal"},
        "Bill": {"pelo": "amarillo", "entradas": True, "ojos": "marron", "gafas": False, "sombrero": False, "barba": True, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "rojo", "boca": "pequeña", "nariz": "pequeña", "orejas": "normal", "cabeza": "grande"},
        "Alfred": {"pelo": "rojo", "entradas": False, "ojos": "azul", "gafas": False, "sombrero": False, "barba": False, "bigote": True, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "normal", "orejas": "grande", "cabeza": "normal"},
        "Max": {"pelo": "negro", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": True, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "grande", "orejas": "normal", "cabeza": "grande"},
        "Tom": {"pelo": "negro", "entradas": True, "ojos": "azul", "gafas": True, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "pequeña", "cabeza": "pequeña"},
        "Alex": {"pelo": "negro", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": True, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "pequeña", "orejas": "normal", "cabeza": "normal"},
        "Sam": {"pelo": "blanco", "entradas": True, "ojos": "marron", "gafas": True, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "pequeña", "cabeza": "grande"},
        "Richard": {"pelo": "marron", "entradas": True, "ojos": "marron", "gafas": False, "sombrero": False, "barba": True, "bigote": True, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "normal", "cabeza": "pequeña"},
        "Paul": {"pelo": "blanco", "entradas": False, "ojos": "marron", "gafas": True, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "grande", "cabeza": "normal"},
        "Maria": {"pelo": "marron", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": True, "barba": False, "bigote": False, "pendientes": True, "sexo": "mujer", "mejilla": "normal", "boca": "normal", "nariz": "pequeña", "orejas": "normal", "cabeza": "normal"},
        "Frans": {"pelo": "rojo", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "pequeña", "orejas": "normal", "cabeza": "grande"},
        "Herman": {"pelo": "rojo", "entradas": True, "ojos": "marron", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "grande", "orejas": "pequeña", "cabeza": "normal"},
        "Bernard": {"pelo": "marron", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": True, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "pequeña", "nariz": "grande", "orejas": "grande", "cabeza": "normal"},
        "Philip": {"pelo": "negro", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": False, "barba": True, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "rojo", "boca": "grande", "nariz": "pequeña", "orejas": "normal", "cabeza": "normal"},
        "Eric": {"pelo": "amarillo", "entradas": False, "ojos": "marron", "gafas": False, "sombrero": True, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "pequeña", "orejas": "pequeña", "cabeza": "grande"},
        "Charles": {"pelo": "amarillo", "entradas": False, "ojos": "azul", "gafas": False, "sombrero": False, "barba": False, "bigote": True, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "pequeña", "orejas": "grande", "cabeza": "normal"},
        "Peter": {"pelo": "blanco", "entradas": False, "ojos": "azul", "gafas": False, "sombrero": False, "barba": False, "bigote": False, "pendientes": False, "sexo": "hombre", "mejilla": "normal", "boca": "grande", "nariz": "grande", "orejas": "pequeña", "cabeza": "grande"},
    }

#Tono piel
#Marcas en la piel


